// import "./node_modules/bootstrap/dist/js/bootstrap";
// import "./node_modules/swiper/package.json"
// import "./node_modules/swiper/swiper-bundle";

$("button#menu").click(function () {
    $(this).toggleClass("is-active");
    $('body').toggleClass("overlay");
});
$("#navbarDropdown").click(function () {
    $(this).toggleClass("is-active");
    $('body').toggleClass("overlay");
});

// SWIPER JS -------------

// Initialize Swiper
const bannerSlider = new Swiper(".banner-slider", {
    slidesPerView: 1,
    spaceBetween: 30,
    pagination: {
        el: ".swiper-pagination",
        clickable: true,
    },
    autoplay: {
        delay: 2500,
        disableOnInteraction: false,
    },
});

const bestSellingSlider = new Swiper(".best-selling-slider", {
    slidesPerView: 1,
    spaceBetween: 30,
    pagination: {
        el: ".swiper-pagination",
        clickable: true,
    },
    autoplay: {
        delay: 2500,
        disableOnInteraction: false,
    },
    breakpoints: {

        768: {
            slidesPerView: 2
        },
        1200: {
            slidesPerView: 4
        }
    },
});

// SMTP Form js
function sendEmail() {
    Email.send({
        Host: "smtp.elasticemail.com",
        // user name for the authenticated account
        Username: "testharshit1@gmail.com",
        // password generated by smtp
        Password: "0550694EB76C983E95893AE4DD7C4D1F97CD",
        // receiver email (Client side)
        To: "testharshit1@gmail.com",
        // receiver email (Client side)
        From: "testharshit1@gmail.com",
        Subject: "New Contact form enquiry",
        // this will fetch user's email from the contact form
        ReplyFrom: document.getElementById("email").value,
        Body: "And this is the body"
    }).then((message) =>
        alert(
            "Thanks for Submitting. Your details are with us and we will shortly connect with you!"
        )
    );
}